### ISSUE TITLE
You cannot set the PORT parameter

### ISSUE THREAD

**Issue by abalad** [ImoucheG/sails-sqlserver-v2#3]
The `sails-sqlserver-2 `plugin removes the port's past configuration, so it doesn't allow you to use another port other than the default one.

![image](https://user-images.githubusercontent.com/5459282/100033821-ab4c7580-2dd9-11eb-81c1-61f534538878.png)

![image](https://user-images.githubusercontent.com/5459282/100033705-76402300-2dd9-11eb-8454-f79da6d72711.png)

**Comment by ImoucheG** [comment]
Hi,
Thanks for the information.
I fixed this bug with this [commit](https://github.com/ImoucheG/sails-sqlserver-v2/commit/daad5c8130f25d2cf57523f2e61498fecd68c339).
