### ISSUE TITLE
One To Many Association Error

### ISSUE THREAD

**Issue by abalad** [ImoucheG/sails-sqlserver-v2#4]
I created a One to Many association, however there is an error with the Adapter
`AdapterError: Unexpected error from database adapter: Cannot convert undefined or null to object`

Model OSATENDIMENTO
![image](https://user-images.githubusercontent.com/5459282/100139057-ae914100-2e6d-11eb-95a5-4376c8377b2e.png)

Model OS
![image](https://user-images.githubusercontent.com/5459282/100139101-bc46c680-2e6d-11eb-9dec-42de462c4c23.png)

![image](https://user-images.githubusercontent.com/5459282/100139195-db455880-2e6d-11eb-86af-8f95fe7b1d07.png)
![image](https://user-images.githubusercontent.com/5459282/100138909-738f0d80-2e6d-11eb-912c-9515ed6f57e9.png)

**Comment by ImoucheG** [comment]
This feature was fix in last commit
